defaults: &defaults
    docker:
        - image: circleci/openjdk:8-jdk
    working_directory: /home/circleci/project

version: 2
jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                keys:
                    - java-dependencies-{{ checksum "./CitibikeApiProducer/build.gradle" }}
            - restore_cache:
                keys:
                    - scala-dependencies-{{ checksum "./RawDataSaver/build.sbt" }}-{{ checksum "./StationConsumer/build.sbt"}}-{{ checksum "./StationTransformerNYC/build.sbt"}}
            - run:
                command: ./sbin/buildAll.sh
            - persist_to_workspace:
                root: /home/circleci/project
                paths:
                    - CitibikeApiProducer/build/
                    - RawDataSaver/target/
                    - StationConsumer/target/
                    - StationTransformerNYC/target/
                    - Monitoring/target/
                    - Monitoring/src/main/resources/scripts/
            - run:
                command: ls /home/circleci/project/
            - save_cache:
                key: scala-dependencies-{{ checksum "./RawDataSaver/build.sbt" }}-{{ checksum "./StationConsumer/build.sbt"}}-{{ checksum "./StationTransformerNYC/build.sbt"}}
                paths:
                    - "~/.ivy2/cache"
            - save_cache:
                key: java-dependencies-{{ checksum "./CitibikeApiProducer/build.gradle" }}
                paths:
                    - "~/.gradle"

    deploy-to-test:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                at: /home/circleci/project
            - add_ssh_keys:
                fingerprints:
                    - "7c:66:56:19:22:c9:99:7f:f9:d0:b5:62:bf:dc:40:81"
            - run:
                command: ./sbin/deployToTest.sh
    deploy-to-prod:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                at: /home/circleci/project
            - add_ssh_keys:
                fingerprints:
                    - "6e:da:45:56:b8:7d:7f:03:9e:67:1f:ba:7a:65:d8:f8"
            - run:
                command: ./sbin/deploy.sh

    e2e-test:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                at: /home/circleci/project
            - add_ssh_keys:
                fingerprints:
                    - "6e:da:45:56:b8:7d:7f:03:9e:67:1f:ba:7a:65:d8:f8"
            - run:
                command: ./e2e-test/e2e.sh

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build:
                filters:
                    branches:
                        only:
                            - master
                            - start
                            - pipeline-runs-tests
            - deploy-to-test:
                requires:
                    - build
            - approve-deploy-to-prod:
                type: approval
                requires:
                    - deploy-to-test
            - deploy-to-prod:
                requires:
                    - approve-deploy-to-prod

