defaults: &defaults
    docker:
        - image: circleci/openjdk:8-jdk
    working_directory: /home/circleci/project

version: 2
jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                keys:
                    - java-dependencies-{{ checksum "./CitibikeApiProducer/build.gradle" }}
            - restore_cache:
                keys:
                    - scala-dependencies-{{ checksum "./RawDataSaver/build.sbt" }}-{{ checksum "./StationConsumer/build.sbt"}}-{{ checksum "./StationTransformerNYC/build.sbt"}}
            - run:
                command: ./sbin/buildAll.sh               
            - persist_to_workspace:
                root: /home/circleci/project
                paths:
                    - CitibikeApiProducer/build/
                    - RawDataSaver/target/
                    - StationConsumer/target/
                    - StationTransformerNYC/target/
            - run:
                command: ls /home/circleci/project/
            - save_cache:
                key: scala-dependencies-{{ checksum "./RawDataSaver/build.sbt" }}-{{ checksum "./StationConsumer/build.sbt"}}-{{ checksum "./StationTransformerNYC/build.sbt"}}
                paths:
                    - "~/.ivy2/cache"
            - save_cache:
                key: java-dependencies-{{ checksum "./CitibikeApiProducer/build.gradle" }}
                paths:
                    - "~/.gradle"

    e2e-test:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                at: /home/circleci/project
            - add_ssh_keys:
                fingerprints:
                    - "9f:64:eb:f4:59:f0:09:be:43:67:96:0e:c3:3b:e6:cd"
            - run:
                command: ./e2e-test/e2e.sh

    deploy:
        <<: *defaults
        steps:
            - checkout
            - attach_workspace:
                at: /home/circleci/project
            - add_ssh_keys:
                fingerprints:
                    - "6e:da:45:56:b8:7d:7f:03:9e:67:1f:ba:7a:65:d8:f8"
            - run:
                command: ./sbin/deploy.sh

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build:
                filters:
                    branches:
                        only: 
                            - master
                            - start
                            - e2e-testing
                            - pipeline-runs-tests
            - approve-deploy:
                type: approval
                requires: 
                    - build
            - deploy:
                requires:
                    - approve-deploy

